// AI and Tech-themed word bank
export const wordList = [
    // AI/ML Terms
    'Neural Network',
    'Deep Learning',
    'Machine Learning',
    'Artificial Intelligence',
    'Backpropagation',
    'Gradient Descent',
    'Convolutional Network',
    'Recurrent Network',
    'Transformer',
    'Attention Mechanism',
    'Overfitting',
    'Regularization',
    'Activation Function',
    'Training Data',
    'Test Data',
    'Supervised Learning',
    'Unsupervised Learning',
    'Reinforcement Learning',
    'Decision Tree',
    'Random Forest',

    // Tech/Programming
    'API Gateway',
    'Microservice',
    'Docker Container',
    'Kubernetes',
    'Load Balancer',
    'Database',
    'Server',
    'Cloud Computing',
    'Virtual Machine',
    'REST API',
    'GraphQL',
    'WebSocket',
    'Authentication',
    'Encryption',
    'Blockchain',
    'Smart Contract',
    'Version Control',
    'Git Repository',
    'Continuous Integration',
    'Deployment Pipeline',

    // Data Science
    'Data Mining',
    'Big Data',
    'Data Warehouse',
    'ETL Process',
    'Feature Engineering',
    'Cross Validation',
    'Confusion Matrix',
    'Precision Recall',
    'Clustering',
    'Classification',
    'Regression',
    'Time Series',
    'Anomaly Detection',
    'Dimensionality Reduction',
    'Principal Component',

    // Software Development
    'Object Oriented',
    'Design Pattern',
    'Singleton Pattern',
    'Factory Pattern',
    'Observer Pattern',
    'Algorithm',
    'Data Structure',
    'Binary Tree',
    'Linked List',
    'Hash Table',
    'Stack Overflow',
    'Queue System',
    'Recursion',
    'Dynamic Programming',
    'Greedy Algorithm',

    // Web Development
    'Frontend Framework',
    'Backend Server',
    'Single Page App',
    'Progressive Web App',
    'Responsive Design',
    'CSS Framework',
    'JavaScript Engine',
    'Browser Cache',
    'Web Security',
    'CORS Policy',

    // DevOps
    'CI CD Pipeline',
    'Configuration Management',
    'Infrastructure Code',
    'Monitoring System',
    'Log Aggregation',
    'Container Orchestration',
    'Service Mesh',
    'Blue Green Deployment',
    'Canary Release',
    'Rolling Update',

    // Miscellaneous
    'Agile Methodology',
    'Scrum Sprint',
    'Code Review',
    'Technical Debt',
    'Refactoring',
    'Unit Testing',
    'Integration Testing',
    'Performance Optimization',
    'Memory Leak',
    'Race Condition'
]

export function getRandomWords(count = 3) {
    const shuffled = [...wordList].sort(() => Math.random() - 0.5)
    return shuffled.slice(0, count)
}
